
```{r}
# load functions
library(CIBRA)
library(BiocParallel)
library(data.table)
```

```{r}
mutation_profile = read.csv("ov_snv_obp_data.csv", header = TRUE, row.names = 1)
sample_ids <- c(rownames(mutation_profile), "sample")
```

```{r}
copy_number_data <- read.csv("ov_cna_obp_data.csv", header = T, row.names = 1)
```

```{r}
#count_data <- fread("TCGA-OV_TCGA_rna_count_data.csv", select = sample_ids)
count_data <- read.csv("TCGA-OV_TCGA_rna_count_data.csv", header = TRUE, row.names = 1)
```

```{r}
colnames(count_data) <- substr(colnames(count_data), 1, 15)
```

```{r}
sample_ids <- colnames(count_data)
rownames(mutation_profile) <- make.names(rownames(mutation_profile))
rownames(copy_number_data) <- make.names(rownames(copy_number_data))
```

```{r}
sample_ids <- intersect(colnames(count_data), rownames(copy_number_data))
copy_number_data <- copy_number_data[sample_ids,]
count_data <- count_data[sample_ids]
```


```{r}
# prepare databraf
goi = c("OBP2A", "OBP2B")
```

```{r}
# filter mutation profile for genes of interest
definition_matrix = copy_number_data[goi]
```

```{r}
definition_matrix$OBP2A <- as.character(definition_matrix$OBP2A)
definition_matrix$OBP2B <- as.character(definition_matrix$OBP2B)
```

```{r}
# fix sample names
rownames(definition_matrix) = make.names(rownames(definition_matrix))
colnames(count_data) = make.names(colnames(count_data))
```

```{r}
count_data <- as.data.frame(count_data)
```

```{r}
# select intersect between definition matrix and count data
sample_list = intersect(colnames(count_data), rownames(definition_matrix))
```

```{r}
# select data
count_data = count_data[sample_list]
definition_matrix = definition_matrix[sample_list,]
```


```{r}
# set parameters for CIBRA
columns = c("OBP2A", "OBP2B")
```


```{r}
control_definition = "0"
confidence = 0.1
iterations = 0
```

```{r}
register(SnowParam(4))
```

```{r}
CIBRA_res = run_CIBRA(count_data, as.data.frame(definition_matrix),
                      columns = columns,
                      control_definition = control_definition,
                      confidence = confidence,
                      iterations = iterations,
                      parallel = TRUE, min_n = 0)
```
```{r}
write.csv(CIBRA_res$CIBRA_results, "cibra_results_ovarian.csv")
write.csv(CIBRA_res$pvalue_results, "pvalue_ovarian.csv")
write.csv(CIBRA_res$fc_results, "fc_ovarian.csv")
write.csv(CIBRA_res$padj_results, "padj_ovarian.csv")
```

```{r}
# calculate the pvalue by comparing to a reference distribution generated with DESeq2
perm_data <- read.csv("TCGA-OV_1000_sample_permutations.csv", header = T, row.names = 1)

# use the gamma test to also calculate a fitted p-value
CIBRA_res_stat <-  permutation_test(CIBRA_res$CIBRA_results, perm_data, test = "gamma")

# print the report table
knitr::kable(CIBRA_res_stat$results)
```

```{r}
# write new CIBRA results with pvalue
write.csv(CIBRA_res_stat$results, "cibra_results_ovarian.csv")
```

```{r}
# read cibra results
CIBRA_results <- read.csv("cibra_results_ovarian.csv")
```

```{r}
# calculate permutation subsamplings to visualize
perm_data$n_case <- round(perm_data$n_case)
perm_data <- perm_data[order(perm_data$n_case),]

diff_val <- abs(perm_data$n_case-117)
match_ids <- which(diff_val == min(diff_val))
mid_id <- round(median(match_ids))

perm_data[(mid_id-50):(mid_id+50),]

# create columns for summary values permutation data
CIBRA_results$med_area <- NA
CIBRA_results$med_prop <- NA
CIBRA_results$q1_area <- NA
CIBRA_results$q3_area <- NA
CIBRA_results$q1_prop <- NA
CIBRA_results$q3_prop <- NA

for (row_id in 1:dim(CIBRA_results)[1]) {
  diff_val <- abs(perm_data$n_case-CIBRA_results[row_id,]$investigated)
  match_ids <- which(diff_val == min(diff_val))
  mid_id <- round(median(match_ids))
  min_id <- mid_id - sample(50:60, 1)
  max_id <- mid_id + sample(50:60, 1)
  
  if (min_id < 0) {
    max_id = max_id + abs(min_id)
    min_id = 0
  }
  perm_cond = perm_data[min_id:max_id,]
  
  CIBRA_results[row_id, "med_area"] = median(perm_cond$significant_area)
  CIBRA_results[row_id, "med_prop"] = median(perm_cond$proportion)
  CIBRA_results[row_id, "q1_area"] = quantile(perm_cond$significant_area)[["25%"]]
  CIBRA_results[row_id, "q3_area"] = quantile(perm_cond$significant_area)[["75%"]]
  CIBRA_results[row_id, "q1_prop"] = quantile(perm_cond$proportion)[["25%"]]
  CIBRA_results[row_id, "q3_prop"] = quantile(perm_cond$proportion)[["75%"]]
}
```

```{r}
require(ggplot2)
library(tidyverse)
require(dplyr)
require(scales)
library(plyr)
library(ggprism)

plot_res <- CIBRA_results %>% select(col, def, investigated, control, sign_area, med_area, q1_area, q3_area, pvalue_sign_area) %>% gather("type", "full_area", -c(col, def, q1_area, q3_area, pvalue_sign_area, investigated, control)) %>% filter(def %in% c(1, -1)) %>% filter(col == "OBP2A")
                                                                                    plot_res$type <- factor(plot_res$type)
plot_res[plot_res$type == "sign_area", c("q1_area", "q3_area")] <- NA
plot_res[plot_res$type == "med_area", "pvalue_sign_area"] <- NA
plot_res[plot_res$type == "med_area", "investigated"] <- 80
plot_res$label <- ""
plot_res[which(plot_res$perm_test_area < 0.05),"label"] <- "significant"
p <- ggplot(plot_res, aes(y = full_area, 
                          x = factor(def), 
                          ymin = q1_area, 
                          ymax = q3_area, fill = pvalue_sign_area)) + 
  geom_point(aes(size = investigated/(investigated+control)*100), shape = 21, 
             color = "black", stroke = 1.5) +
  geom_errorbar(width = .08, color = "black", alpha=.6) +
  #facet_wrap(~ col, scales = "free") + 
  ylab("CIBRA impact score (Significant Area)") + xlab("") + 
  scale_fill_continuous('p-value', low = "#ffffcc", high = "#800026", 
                        breaks = c(0.001, 0.01, 0.05, 0.25, 1),
                        trans = compose_trans("log10", "reverse"),
                        limits = c(1,0.000001)) +
  scale_size_area(name = "Cases (%)", 
                  breaks = c(25, 50, 75, 100),
                  limit = c(0,100), max_size = 12) + 
  scale_x_discrete(labels = c('1' = "gain", 
                              '-1' = "loss")) +
  xlab("OBP2A") +
  theme_prism() +
  theme(axis.text = element_text(face="bold", size = 16),
        axis.title = element_text(face = "bold", size = 22),
        legend.text = element_text(face = "bold", size = 12),
        legend.title = element_text(face="bold", size=14),
        panel.grid.major=element_line(colour="lightgrey")) +
  guides(size = guide_legend(reverse = TRUE, override.aes=list(fill = "darkgrey")))

print(p)
pdf("cibra_figure_ovarian_OBP2A.pdf")
print(p)
dev.off()
png("cibra_figure_ovarian_OBP2A.png")
print(p)
dev.off()
```

```{r}
plot_res <- CIBRA_results %>% select(col, def, investigated, control, sign_area, med_area, q1_area, q3_area, pvalue_sign_area) %>% gather("type", "full_area", -c(col, def, q1_area, q3_area, pvalue_sign_area, investigated, control)) %>% filter(def %in% c(1, -1)) %>% filter(col == "OBP2B")
                                                                                    plot_res$type <- factor(plot_res$type)
plot_res[plot_res$type == "sign_area", c("q1_area", "q3_area")] <- NA
plot_res[plot_res$type == "med_area", "pvalue_sign_area"] <- NA
plot_res[plot_res$type == "med_area", "investigated"] <- 80
plot_res$label <- ""
plot_res[which(plot_res$perm_test_area < 0.05),"label"] <- "significant"
p <- ggplot(plot_res, aes(y = full_area, 
                          x = factor(def), 
                          ymin = q1_area, 
                          ymax = q3_area, fill = pvalue_sign_area)) + 
  geom_point(aes(size = investigated/(investigated+control)*100), shape = 21, 
             color = "black", stroke = 1.5) +
  geom_errorbar(width = .08, color = "black", alpha=.6) +
  #facet_wrap(~ col, scales = "free") + 
  ylab("CIBRA impact score (Significant Area)") + xlab("") + 
  scale_fill_continuous('p-value', low = "#ffffcc", high = "#800026", 
                        breaks = c(0.001, 0.01, 0.05, 0.25, 1),
                        trans = compose_trans("log10", "reverse"),
                        limits = c(1,0.000001)) +
  scale_size_area(name = "Cases (%)", 
                  breaks = c(25, 50, 75, 100),
                  limit = c(0,100), max_size = 12) + 
  scale_x_discrete(labels = c('1' = "gain", 
                              '-1' = "loss")) +
  xlab("OBP2A") +
  theme_prism() +
  theme(axis.text = element_text(face="bold", size = 16),
        axis.title = element_text(face = "bold", size = 22),
        legend.text = element_text(face = "bold", size = 12),
        legend.title = element_text(face="bold", size=14),
        panel.grid.major=element_line(colour="lightgrey")) +
  guides(size = guide_legend(reverse = TRUE, override.aes=list(fill = "darkgrey")))

print(p)
pdf("cibra_figure_ovarian_OBP2B.pdf")
print(p)
dev.off()
png("cibra_figure_ovarian_OBP2B.png")
print(p)
dev.off()
```


```{r}
# look at expression of OBP2A and OBP2B
obp2a_fc <- CIBRA_res$fc_results["OBP2A",]
obp2a_pvalue <- CIBRA_res$pvalue_results["OBP2A",]
obp2a_adj_pvalue <- CIBRA_res$padj_results["OBP2A",]
obp2b_fc <- CIBRA_res$fc_results["OBP2B",]
obp2b_pvalue <- CIBRA_res$pvalue_results["OBP2B",]
obp2b_adj_pvalue <- CIBRA_res$padj_results["OBP2B",]

# make a table (dataframe) from these results
write.csv(CIBRA_res$fc_results["OBP2A",], "obp2a_fc.csv")
write.csv(CIBRA_res$padj_results["OBP2A",], "obp2a_adj_pvalue.csv")
write.csv(CIBRA_res$fc_results["OBP2B",], "obp2b_fc.csv")
write.csv(CIBRA_res$padj_results["OBP2B",], "obp2b_adj_pvalue.csv")

# combine adjusted pvalue and fc
obp2a <- read.csv("obp2a_adj_pvalue.csv", check.names = FALSE)
obp2b <- read.csv("obp2b_adj_pvalue.csv", check.names = FALSE)
obp2a <- read.csv("obp2a_fc.csv", check.names = FALSE)
obp2b <- read.csv("obp2b_fc.csv", check.names = FALSE)

adjpvalue_merged <- rbind(obp2a, obp2b)
fc_merged <- rbind(obp2a, obp2b)

write.csv(adjpvalue_merged, "adjpvalue_merged.csv", row.names = FALSE)  
write.csv(fc_merged, "fc_merged.csv", row.names = FALSE)

```

