---
title: "CIBRA_ovarian_Mifen"
output: Although Soufyan already run ovarian cancer for me in first tutorial, I would want to rerun it to have practice more, and to have output data to check with Soufyan_tutorial on ovarian to see if I made some mistakes. 
folder: All files in ovarian_Mifen.
---

```{r}
# load functions
library(DESeq2)
library(dplyr)
library(ggplot2)
library(gridExtra)
#library(data.table)
```

```{r}
mutation_profile = read.csv("../data/datasets/snv_data/ov_snv_obp_data.csv", header = TRUE, row.names = 1)
sample_ids <- c(rownames(mutation_profile), "sample")
```

```{r}
copy_number_data <- read.csv("../data/datasets/cnv_data/ov_cna_obp_data.csv", header = T, row.names = 1)
```

```{r}
#count_data <- fread("TCGA-OV_TCGA_rna_count_data.csv", select = sample_ids)
count_data <- read.csv("../data/datasets/rna_data/TCGA-OV_TCGA_rna_count_data.csv", header = TRUE, row.names = 1)
```

```{r}
colnames(count_data) <- substr(colnames(count_data), 1, 15)
```

```{r}
sample_ids <- colnames(count_data)
rownames(mutation_profile) <- make.names(rownames(mutation_profile))
rownames(copy_number_data) <- make.names(rownames(copy_number_data))
```

```{r}
sample_ids <- intersect(intersect(colnames(count_data), rownames(copy_number_data)), rownames(mutation_profile))
copy_number_data <- copy_number_data[sample_ids,]
mutation_profile <- mutation_profile[sample_ids,]
count_data <- count_data[sample_ids]
```

```{r}
# create a design matrix for obp2A and obp2b with SNV and CNV status

# there are no SNVs for OBP2B -> set it to WT
mutation_profile$OBP2B <- "WT"

design_matrix <- copy_number_data

design_matrix$OBP2A <- factor(paste(copy_number_data$OBP2A, mutation_profile$OBP2A, sep = "_"))
design_matrix$OBP2B <- factor(paste(copy_number_data$OBP2B, mutation_profile$OBP2B, sep = "_"))

# rename the categories for plotting, check which categories there are in the data
design_matrix <- design_matrix %>% mutate(OBP2A = recode(OBP2A, `-1_SNV` = "Loss_SNV", `-1_WT` = "Loss",
                                        `0_WT` = "WT", `1_WT` = "Gain", `2_WT` = "Amplification"),
                         OBP2B = recode(OBP2B, `-1_WT` = "Loss", `0_WT` = "WT",
                                        `1_WT` = "Gain", `2_WT` = "Amplification"))

```

```{r}
dds <- DESeqDataSetFromMatrix(countData = count_data,
                              colData = design_matrix,
                              design = ~ OBP2A + OBP2B)

dds <- DESeq(dds)
```

```{r}
# Plot the expression as boxplots. Change the theme of the plots to make them look nicer if you want.

d <- plotCounts(dds, gene="OBP2A", intgroup="OBP2A", 
                returnData=TRUE)

# filter the conditions with very few samples (Loss_SNV and amplification)
obp2a <- ggplot(d[!(d$OBP2A %in% c("Loss_SNV", "Amplification")),], aes(x=factor(OBP2A, 
                                                                       levels = c("WT", "Loss", "Gain")), 
                                                              y=count)) + 
  geom_point(position=position_jitter(w=0.1,h=0)) + 
  geom_boxplot(aes(color = OBP2A), width = 0.1, lwd = 1, alpha = 0.3) +
  scale_y_log10(breaks=c(1,10,100,1000, 10000)) + xlab("OBP2A") + ylab("Normalized counts") +
  stat_summary(fun = median, geom = "text", 
               aes(label=sprintf("%1.1f", ..y..)), fontface = "bold",
               position = position_nudge(x=0.35), size=3, color = "black") +
  theme(legend.position = "None")

d <- plotCounts(dds, gene="OBP2B", intgroup="OBP2B", 
                returnData=TRUE)

# filter the conditions with very few samples (Loss_SNV and amplification)
obp2b <- ggplot(d[!(d$OBP2B %in% c("Amplification")),], aes(x=factor(OBP2B, 
                                                                       levels = c("WT", "Loss", "Gain")), 
                                                              y=count)) + 
  geom_point(position=position_jitter(w=0.1,h=0)) + 
  geom_boxplot(aes(color = OBP2B), width = 0.1, lwd = 1, alpha = 0.3) +
  scale_y_log10(breaks=c(1,10,100,1000, 10000)) + xlab("OBP2B") + ylab("Normalized counts") +
  stat_summary(fun = median, geom = "text", 
               aes(label=sprintf("%1.1f", 10^..y..)), fontface = "bold",
               position = position_nudge(x=0.2), size=3, color = "black") +
  theme(legend.position = "None")

grid.arrange(obp2a, obp2b, nrow = 1)


```
