---
title: "CIBRA_ovarian_Mifen"
output: Although Soufyan already run ovarian cancer for me in first tutorial, I would want to rerun it to have practice more, and to have output data to check with Soufyan_tutorial on ovarian to see if I made some mistakes. 
folder: All files in ovarian_Mifen.
---

```{r}
# load functions
library(CIBRA)
library(BiocParallel)
library(data.table)
```

```{r}
mutation_profile = read.csv("ov_snv_obp_data.csv", header = TRUE, row.names = 1)
sample_ids <- c(rownames(mutation_profile), "sample")
```

```{r}
copy_number_data <- read.csv("ov_cna_obp_data.csv", header = T, row.names = 1)
```

```{r}
#count_data <- fread("TCGA-OV_TCGA_rna_count_data.csv", select = sample_ids)
count_data <- read.csv("TCGA-OV_TCGA_rna_count_data.csv", header = TRUE, row.names = 1)
```

```{r}
colnames(count_data) <- substr(colnames(count_data), 1, 15)
```

```{r}
sample_ids <- colnames(count_data)
rownames(mutation_profile) <- make.names(rownames(mutation_profile))
rownames(copy_number_data) <- make.names(rownames(copy_number_data))
```

```{r}
sample_ids <- intersect(colnames(count_data), rownames(copy_number_data))
copy_number_data <- copy_number_data[sample_ids,]
count_data <- count_data[sample_ids]
```


```{r}
# prepare databraf
goi = c("OBP2A", "OBP2B")
```

```{r}
# filter mutation profile for genes of interest
definition_matrix = copy_number_data[goi]
```

```{r}
definition_matrix$OBP2A <- as.character(definition_matrix$OBP2A)
definition_matrix$OBP2B <- as.character(definition_matrix$OBP2B)
```

```{r}
# fix sample names
rownames(definition_matrix) = make.names(rownames(definition_matrix))
colnames(count_data) = make.names(colnames(count_data))
```

```{r}
count_data <- as.data.frame(count_data)
```

```{r}
# select intersect between definition matrix and count data
sample_list = intersect(colnames(count_data), rownames(definition_matrix))
```

```{r}
# select data
count_data = count_data[sample_list]
definition_matrix = definition_matrix[sample_list,]
```


```{r}
# set parameters for CIBRA
columns = c("OBP2A", "OBP2B")
```


```{r}
control_definition = "0"
confidence = 0.1
iterations = 0
```

```{r}
register(SnowParam(4))
```

```{r}
CIBRA_res = run_CIBRA(count_data, as.data.frame(definition_matrix),
                      columns = columns,
                      control_definition = control_definition,
                      confidence = confidence,
                      iterations = iterations,
                      parallel = TRUE, min_n = 0)
```
```{r}
write.csv(CIBRA_res$CIBRA_results, "cibra_results_ovarian_mifen.csv")
write.csv(CIBRA_res$pvalue_results, "pvalue_ovarian_mifen.csv")
write.csv(CIBRA_res$fc_results, "fc_ovarian_mifen.csv")
write.csv(CIBRA_res$padj_results, "padj_ovarian_mifen.csv")
```

```{r}
# calculate the pvalue by comparing to a reference distribution generated with DESeq2
perm_data <- read.csv("TCGA-OV_1000_sample_permutations.csv", header = T, row.names = 1)

# use the gamma test to also calculate a fitted p-value
CIBRA_res_stat <-  permutation_test(CIBRA_res$CIBRA_results, perm_data, test = "gamma")

# print the report table
knitr::kable(CIBRA_res_stat$results)
```

```{r}
# write new CIBRA results with pvalue
write.csv(CIBRA_res_stat$results, "cibra_results_ovarian_mifen.csv")
```

```{r}
require(ggplot2)
require(dplyr)
require(scales)

# visualize the results
plot_data <- CIBRA_res_stat$results %>% select(def, col, investigated, control, sign_area, 
                                 pvalue_sign_area)

plot_data$def_col <- paste0(plot_data$col, "_", plot_data$def)
p <- ggplot(plot_data, aes(y = as.numeric(sign_area), 
                          x = factor(def_col), fill = pvalue_sign_area)) + 
  geom_point(aes(size = as.numeric(investigated)/(as.numeric(investigated) 
                                                  + as.numeric(control))*100), 
             shape = 21, 
             color = "black", stroke = 1.5) +
  ylab("CIBRA impact score (Significant Area)") + xlab("") + 
  scale_fill_continuous('p-value', low = "#ffffcc", high = "#800026", 
                        breaks = c(0.001, 0.01, 0.05, 0.25, 1),
                        trans = compose_trans("log10", "reverse"),
                        limits = c(1,0.00000000001)) +
  scale_size_area(name = "Cases (%)", 
                  breaks = c(25, 50, 75, 100),
                  limit = c(0,100), max_size = 8) +
  ylim(c(0,0.5)) +
  theme_minimal() +
  guides(size = guide_legend(reverse = TRUE, override.aes=list(fill = "darkgrey")))

print(p)
pdf("cibra_figure_ovarian.pdf")
print(p)
dev.off()
```

```{r}
# look at expression of OBP2A and OBP2B
obp2a_fc <- CIBRA_res$fc_results["OBP2A",]
obp2a_adj_pvalue <- CIBRA_res$padj_results["OBP2A",]
obp2b_fc <- CIBRA_res$fc_results["OBP2B",]
obp2b_adj_pvalue <- CIBRA_res$padj_results["OBP2B",]

# make a table (dataframe) from these results
write.csv(CIBRA_res$fc_results["OBP2A",], "obp2a_fc")
write.csv(CIBRA_res$padj_results["OBP2A",], "obp2a_adj_pvalue")
write.csv(CIBRA_res$fc_results["OBP2B",], "obp2b_fc")
write.csv(CIBRA_res$padj_results["OBP2B",], "obp2b_adj_pvalue")
```

