
```{r}
# load functions
library(DESeq2)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(ggprism)
library(ggbeeswarm)
#library(data.table)
```

```{r}
mutation_profile = read.csv("melanoma_snv_obp_data.csv", header = TRUE, row.names = 1)
sample_ids <- c(rownames(mutation_profile), "sample")
```

```{r}
copy_number_data <- read.csv("melanoma_cna_obp_data.csv", header = T, row.names = 1)
```

```{r}
#count_data <- fread("TCGA-OV_TCGA_rna_count_data.csv", select = sample_ids)
count_data <- read.csv("TCGA-SKCM_TCGA_rna_count_data.csv", header = TRUE, row.names = 1)
```

```{r}
colnames(count_data) <- substr(colnames(count_data), 1, 15)
```

```{r}
sample_ids <- colnames(count_data)
rownames(mutation_profile) <- make.names(rownames(mutation_profile))
rownames(copy_number_data) <- make.names(rownames(copy_number_data))
```

```{r}
# Remove rows with any NA in the mutation_profile data frame
#mutation_profile <- na.omit(mutation_profile)

# Alternative using logical subsetting
#mutation_profile <- mutation_profile[complete.cases(mutation_profile), ]

# Remove rows where the OBP2A column in mutation_profile has NA
#mutation_profile <- mutation_profile[!is.na(mutation_profile$OBP2A), ]

# Using dplyr's filter function
#library(dplyr)
#mutation_profile <- mutation_profile %>% filter(!is.na(OBP2A))

# Check if there are NA values in each column
#colSums(is.na(mutation_profile))

# Screen out NA values from mutation_profile
#mutation_profile <- mutation_profile[complete.cases(mutation_profile), ]

# Screen out NA values from copy_number_data
#copy_number_data <- copy_number_data[complete.cases(copy_number_data), ]

# Screen out NA values from count_data
#count_data <- count_data[complete.cases(count_data), ]

#sample_ids <- intersect(intersect(colnames(count_data), rownames(copy_number_data)), rownames(mutation_profile))

#mutation_profile <- mutation_profile[complete.cases(mutation_profile), ]
#copy_number_data <- copy_number_data[complete.cases(copy_number_data), ]
#count_data <- count_data[complete.cases(count_data), ]

```

```{r}
sample_ids <- intersect(intersect(colnames(count_data), rownames(copy_number_data)), rownames(mutation_profile))
copy_number_data <- copy_number_data[sample_ids,]
mutation_profile <- mutation_profile[sample_ids,]
count_data <- count_data[sample_ids]
```

```{r}
# create a design matrix for obp2A and obp2b with SNV and CNV status
# there are no SNVs for OBP2B -> set it to WT
#mutation_profile$OBP2B <- "WT"
design_matrix <- copy_number_data
design_matrix$OBP2A <- factor(paste(copy_number_data$OBP2A, mutation_profile$OBP2A, sep = "_"))
design_matrix$OBP2B <- factor(paste(copy_number_data$OBP2B, mutation_profile$OBP2B, sep = "_"))
# rename the categories for plotting, check which categories there are in the data
design_matrix <- design_matrix %>% mutate(OBP2A = recode(OBP2A, `-1_WT` = "Loss", `-1_SNV` = "Loss & SNV",  
                                        `0_WT` = "WT", `1_WT` = "Gain", `0_SNV` = "SNV"),
                         OBP2B = recode(OBP2B, `-1_WT` = "Loss",`-2_WT` = "Deep deletion", `0_WT` = "WT",
                                        `1_WT` = "Gain", `0_SNV` = "SNV", `-1_SNV` = "Loss & SNV"))

# remove groups with less than 5 samples
design_matrix <- design_matrix %>% tibble::rownames_to_column(var = "rownames") %>% group_by(OBP2A, OBP2B) %>% filter(n() >= 5) %>% ungroup() %>% tibble::column_to_rownames(var = "rownames")
design_matrix$OBP2B <- factor(design_matrix$OBP2B)
design_matrix$OBP2A <- factor(design_matrix$OBP2A)
```

```{r}
dds_obp2a <- DESeqDataSetFromMatrix(countData = count_data[,rownames(design_matrix)],
                              colData = design_matrix,
                              design = ~ OBP2A)
dds_obp2b <- DESeqDataSetFromMatrix(countData = count_data[,rownames(design_matrix)],
                              colData = design_matrix,
                              design = ~ OBP2B)
dds_obp2a <- DESeq(dds_obp2a, quiet = FALSE)
dds_obp2b <- DESeq(dds_obp2b, quiet = FALSE)
```

```{r}
# Plot the expression as boxplots. Change the theme of the plots to make them look nicer if you want.
d_obp2a <- plotCounts(dds_obp2a, gene="OBP2A", intgroup="OBP2A", 
                returnData=TRUE)
# filter the conditions with very few samples (Loss_SNV and amplification)
obp2a <- ggplot(d_obp2a[!(d_obp2a$OBP2A %in% c("Loss_SNV", "Amplification")),], aes(x=factor(OBP2A, 
                                                                       levels = c("WT", "Loss", "Gain")), 
                                                              y=count+1)) + 
  geom_quasirandom(color = "darkgrey") + 
  geom_boxplot(aes(fill = OBP2A), width = 0.1, lwd = 1, alpha = 0.5) +
  scale_y_log10(breaks=c(1,10,100,1000, 10000)) + xlab("OBP2A") + ylab("Normalized RNA expression") +
  stat_summary(fun = median, geom = "text", 
               aes(label=sprintf("%1.1f", ..y..)), fontface = "bold",
               position = position_nudge(x=0.35), size=3, color = "black") + theme_prism() + 
  theme(legend.position = "None")
d <- plotCounts(dds_obp2b, gene="OBP2B", intgroup="OBP2B", 
                returnData=TRUE)
# filter the conditions with very few samples (Loss_SNV and amplification)
obp2b <- ggplot(d[!(d$OBP2B %in% c("Amplification")),], aes(x=factor(OBP2B, 
                                                                       levels = c("WT", "Loss", "Gain")), 
                                                              y=count+1)) + 
  geom_quasirandom(color = "darkgrey") + 
  geom_boxplot(aes(fill = OBP2B), width = 0.1, lwd = 1, alpha = 0.5) +
  scale_y_log10(breaks=c(1,10,100,1000, 10000)) + xlab("OBP2B") + ylab("Normalized RNA expression") +
  stat_summary(fun = median, geom = "text", 
               aes(label=sprintf("%1.1f", ..y..)), fontface = "bold",
               position = position_nudge(x=0.35), size=3, color = "black") +
  theme_prism() +theme(legend.position = "None")
pdf("melanoma_cancer_obp_boxplot.pdf", height = 6, width = 12)
grid.arrange(obp2a, obp2b, nrow = 1)
dev.off()


```

```{r}
# include significance of DE analysis to the figure
```

